cmsapp/urls.py
from django.urls import path, include
from .views import *
from .models import *
app_name = 'cmsapp'


urlpatterns = [

    # Bachelor Pass nabhako bharabhuri haru ko lagi

    path('receptionist/registration/', ReceptionistRegistrationView.as_view(),
         name='receptionistregistration'),
    path('student/registration/', StudentRegistrationView.as_view(),
         name='studentregistration'),
    path('teacher/registration/', TeacherRegistrationView.as_view(),
         name='teacherregistration'),
    path('consultant/registration/', ConsultantRegistrationView.as_view(),
         name='consultantregistration'),
    path('lead/registration/', LeadRegistrationView.as_view(),
         name='leadregistration'),
    path('visitor/registration/', VisitorRegistrationView.as_view(),
         name='visitorregistration'),
    path('admin/registration/', AdminRegistrationView.as_view(),
         name='adminregistration'),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # admin panel urls

    path('adminpanel/', AdminPanelView.as_view(), name='adminpanel'),
    path('admin/list/', AdminListView.as_view(), name='adminlist'),
    path('adminconsultant/list/', AdminConsultantListView.as_view(),
         name='adminconsultantlist'),
    path('adminlead/list/', AdminLeadListView.as_view(),
         name='adminleadlist'),
    path('adminteacher/list/', AdminTeacherListView.as_view(),
         name='adminteacherlist'),
    path('adminreceptionist/list/', AdminReceptionistListView.as_view(),
         name='adminreceptionistlist'),
    path('adminstudent/list/', AdminStudentListView.as_view(),
         name='adminstudentlist'),
    path('adminvisitor/list/', AdminVisitorListView.as_view(),
         name='adminvisitorlist'),
    path('admintask/list/', AdminTaskListView.as_view(),
         name='admintasklist'),
    path('adminappointment/list/', AdminAppointmentListView.as_view(),
         name='adminappointmentlist'),
    path('adminfeed/list/', AdminFeedListView.as_view(),
         name='adminfeedlist'),

    # adminpanel feed create views

    path('adminfeed/create/', AdminFeedCreateView.as_view(), name='adminfeedcreate'),
    path('adminfeed/<int:pk>/comment/create/',
         AdminFeedCommentCreateView.as_view(), name='adminfeedcommentcreate'),
    path('adminfeed/<int:pk>/delete/',
         AdminFeedDeleteView.as_view(), name='adminfeeddelete'),
    path('adminfeed/<int:pk1>/comment/<int:pk2>/delete/',
         AdminFeedCommentDeleteView.as_view(), name='adminfeedcommentdelete'),

    # adminpanel detail views urls

    path('admin/<int:pk>/detail/',
         AdminDetailView.as_view(), name='admindetail'),
    path('adminconsultant/<int:pk>/detail/',
         AdminConsultantDetailView.as_view(), name='adminconsultantdetail'),
    path('adminreceptionist/<int:pk>/detail/',
         AdminReceptionistDetailView.as_view(), name='adminreceptionistdetail'),
    path('student/<int:pk>/detail/',
         AdminStudentDetailView.as_view(), name='adminstudentdetail'),
    path('adminlead/<int:pk>/detail/',
         AdminLeadDetailView.as_view(), name='adminleaddetail'),
    path('adminteacher/<int:pk>/detail/',
         AdminTeacherDetailView.as_view(), name='adminteacherdetail'),

    # admin create views urls
    path('adminteacher/registration/', AdminTeacherRegistrationView.as_view(),
         name='adminteacherregistration'),
    path('adminreceptionist/registration/', AdminReceptionistRegistrationView.as_view(),
         name='adminreceptionistregistration'),
    path('adminstudent/registration/', AdminStudentRegistrationView.as_view(),
         name='adminstudentregistration'),
    path('admintask/create/', AdminTaskCreateView.as_view(),
         name='admintaskcreate'),

    # adminpanel update views urls
    path('consultant/<int:pk>/update', ConsultantUpdateView.as_view(),
         name='consultantupdate'),
    path('admin/<int:pk>/update', AdminUpdateView.as_view(), name='adminupdate'),
    path('adminlead/<int:pk>/update', LeadUpdateView.as_view(),
         name='adminleadupdate'),
    path('adminteacher/<int:pk>/update', AdminTeacherUpdateView.as_view(),
         name='adminteacherupdate'),
    path('adminreceptionist/<int:pk>/update', AdminReceptionistUpdateView.as_view(),
         name='adminreceptionistupdate'),
    path('adminstudent/<int:pk>/update', AdminStudentUpdateView.as_view(),
         name='adminstudentupdate'),

    # adminpanel delete views url
    path('adminconsultant/<int:pk>/delete',
         AdminConsultantDeleteView.as_view(), name='adminconsultantdelete'),
    path('adminlead/<int:pk>/delete',
         AdminLeadDeleteView.as_view(), name='adminleaddelete'),
    path('adminteacher/<int:pk>/delete',
         AdminTeacherDeleteView.as_view(), name='adminteacherdelete'),
    path('adminreceptionist/<int:pk>/delete',
         AdminReceptionistDeleteView.as_view(), name='adminreceptionistdelete'),
    path('adminstudent/<int:pk>/delete',
         AdminStudentDeleteView.as_view(), name='adminstudentdelete'),
    path('adminvisitor/<int:pk>/delete',
         AdminVisitorDeleteView.as_view(), name='adminvisitordelete'),
    path('admintask/<int:pk>/delete',
         AdminTaskDeleteView.as_view(), name='admintaskdelete'),





    # student panel urls

    path('studentpanel/', StudentPanelView.as_view(), name='studentpanel'),
    path('studentteacher/list/', StudentTeacherListView.as_view(),
         name='studentteacherlist'),
    path('studentreceptionist/list/', StudentReceptionistListView.as_view(),
         name='studentreceptionistlist'),

    # studentpanel details urls

    path('student/<int:pk>/detail/',
         StudentDetailView.as_view(), name='studentdetail'),

    # studentpanel feed create views

    path('studentfeed/create/', StudentFeedCreateView.as_view(),
         name='studentfeedcreate'),
    path('studentfeed/<int:pk>/comment/create/',
         StudentFeedCommentCreateView.as_view(), name='studentfeedcommentcreate'),
    path('studentfeed/<int:pk>/delete/',
         StudentFeedDeleteView.as_view(), name='studentfeeddelete'),
    path('studentfeed/<int:pk1>/comment/<int:pk2>/delete/',
         StudentFeedCommentDeleteView.as_view(), name='studentfeedcommentdelete'),


    # teacher panel urls

    path('teacherpanel/', TeacherPanelView.as_view(), name='teacherpanel'),
    path('teacherconsultant/list/', TeacherConsultantListView.as_view(),
         name='teacherconsultantlist'),
    path('teacher/list/', TeacherListView.as_view(),
         name='teacherlist'),
    path('teacherreceptionist/list/', TeacherReceptionistListView.as_view(),
         name='teacherreceptionistlist'),
    path('teacherstudent/list/', TeacherStudentListView.as_view(),
         name='teacherstudentlist'),
    path('teachertask/list/', TeacherTaskListView.as_view(),
         name='teachertasklist'),
    path('teacheruniversity/list/', TeacherUniversityListView.as_view(),
         name='teacheruniversitylist'),
    path('teacherfeed/list/', TeacherFeedListView.as_view(), name='teacherfeedlist'),
    path('teacherstudymaterials/list/',
         TeacherStudyMaterialsListView.as_view(), name='teacherstudymaterialslist'),

    # teacherpanel feed create views

    path('teacherfeed/create/', TeacherFeedCreateView.as_view(),
         name='teacherfeedcreate'),
    path('teacherfeed/<int:pk>/comment/create/',
         TeacherFeedCommentCreateView.as_view(), name='teacherfeedcommentcreate'),
    path('teacherfeed/<int:pk>/delete/',
         TeacherFeedDeleteView.as_view(), name='teacherfeeddelete'),
    path('teacherfeed/<int:pk1>/comment/<int:pk2>/delete/',
         TeacherFeedCommentDeleteView.as_view(), name='teacherfeedcommentdelete'),


    # teacherpanel details views urls

    path('teacher/<int:pk>/detail/',
         TeacherDetailView.as_view(), name='teacherdetail'),
    path('teacherstudent/<int:pk>/detail/',
         TeacherStudentDetailView.as_view(), name='teacherstudentdetail'),

    # teacherpanel create views urls

    path('teacherstudymaterials/create/',
         TeacherStudyMaterialsCreateView.as_view(), name='teacherstudymaterialscreate'),

    # teacherpanel update views urls
    path('teacherstudymaterials/<int:pk>/update/',
         TeacherStudyMaterialsUpdateView.as_view(), name='teacherstudymaterialsupdate'),

    # teacherpanel delete views urls
    path('teacherstudymaterials/<int:pk>/delete/',
         TeacherStudyMaterialsDeleteView.as_view(), name='teacherstudymaterialsdelete'),

    # consultant panel urls

    path('consultantpanel/', ConsultantPanelView.as_view(), name='consultantpanel'),
    path('consultant/list/', ConsultantListView.as_view(),
         name='consultantlist'),
    path('consultantlead/list/', ConsultantLeadListView.as_view(),
         name='consultantleadlist'),
    path('consultantteacher/list/', ConsultantTeacherListView.as_view(),
         name='consultantteacherlist'),
    path('consultantreceptionist/list/', ConsultantReceptionistListView.as_view(),
         name='consultantreceptionistlist'),
    path('consultantstudent/list/', ConsultantStudentListView.as_view(),
         name='consultantstudentlist'),
    path('consultantvisitor/list/', ConsultantVisitorListView.as_view(),
         name='consultantvisitorlist'),
    path('consultanttask/list/', ConsultantTaskListView.as_view(),
         name='consultanttasklist'),
    path('consultantappointment/list/', ConsultantAppointmentListView.as_view(),
         name='consultantappointmentlist'),
    path('consultantfeed/list/', ConsultantFeedListView.as_view(),
         name='consultantfeedlist'),
    path('consultantdocument/create/', ConsultantDocumentCreateView.as_view(),
         name='consultantdocumentcreate'),

    # consultant create view urls
    path('consultanttask/create/', ConsultantTaskCreateView.as_view(),
         name='consultanttaskcreate'),
    path('consultantappointment/create/', ConsultantAppointmentCreateView.as_view(),

cmsproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmsapp.urls', namespace='cmsapp')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/admintemplates/adminconsultantdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block body %}
<div style="margin:20px 300px; margin-right: 100px;">
<div class="pcoded-content">
<div class="pcoded-inner-content">

<div class="main-body">
<div class="page-wrapper">

<div class="page-header">
<div class="row align-items-end">
<div class="col-lg-8">
<div class="page-header-title">
<div class="d-inline">
<h4>User Profile</h4>
<span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
</div>
</div>
</div>

</div>
</div>
</div>
</div>
</div>
</div>


<div class="page-body">

<div class="row">
<div class="col-lg-12">
<div class="cover-profile">
 <div class="profile-bg-img">
<img class="profile-bg-img img-fluid" src="{% static 'files/assets/images/user-profile/bg-img1.jpg' %}" alt="bg-img">
<div class="card-block user-info">
<div class="col-md-12">
<div class="media-left">
<a href="#" class="profile-image">
<img class="user-img img-radius" src="{{consultantdetail.image.url}}" alt="user-img" style="width: 100px; height: 100px;">
</a>
</div>
<div class="media-body row">
<div class="col-lg-12">
<div class="user-title">
<h2>{{adminconsultantdetail.name}}</h2>
</div>
</div>
<div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="row">
<div class="col-lg-12">


<div class="tab-content">

<!-- <div class="tab-pane active" id="personal" role="tabpanel"> -->

<div class="card">
<div class="card-header">
<h5 class="card-header-text">About Me</h5>

</div>
<div class="card-block">
<div class="view-info">
<div class="row">
<div class="col-lg-12">
<div class="general-info">
<div class="row">
<div class="col-lg-12 col-xl-6">
<div class="table-responsive">
<table class="table m-0">
<tbody>
<tr>
<th scope="row">Full Name</th>
<td>{{adminconsultantdetail.name}}</td>
</tr>
<tr>
<th scope="row">Phone</th>
<td>{{adminconsultantdetail.phone}}</td>
</tr>
<tr>
<th scope="row">Address</th>
 <td>{{adminconsultantdetail.address}}</td>
</tr>
<tr>
<th scope="row">Email</th>
<td>{{adminconsultantdetail.email}}</td>
</tr>

</tbody>
</table>
</div>
</div>
<!-- 
</div> -->

</div>

</div>

</div>

</div>

</div>
<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-header">
<h5 class="card-header-text">Description About Me</h5>

</div>
<div class="card-block user-desc">
<div class="view-desc">
<p>{{consultantdetail.about}}</p>
</div>

{% endblock %}

templates/admintemplates/adminconsultantlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block active2 %}active{% endblock %}
{% block css %}
{% endblock %}
{% block body %}
<div class="dt-responsive table-responsive">
<button class="btn btn-out-dotted btn-info btn-square pull-right" ><a href="{% url 'cmsapp:consultantregistration' %}">Add Consultant</a></button>
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>S.N</th>
<th>user</th>
<th>Name</th>
<th>Address</th>
<th>Phone</th>
<th>Email</th>
<th>Action</th>
</tr>
</thead>
<tbody>
    {% for consultant in adminconsultantlist %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{consultant.user}}</td>
<td><a href="{% url 'cmsapp:adminconsultantdetail' consultant.id %}">{{consultant.name}}</a></td>
<td>{{consultant.address}}</td>
<td>{{consultant.phone}}</td>
<td>{{consultant.email}}</td>
<td><a href="{% url 'cmsapp:consultantupdate' consultant.id %}" class="btn btn-link btn-info btn-just-icon edit"> 
<i class="material-icons">update</i>
</a>
<a href="{% url 'cmsapp:adminconsultantdelete' consultant.id %}" class="btn btn-link btn-info btn-just-icon delete">
<i class="material-icons">delete</i>
</a></td>

</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

templates/admintemplates/adminfeedlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block active10 %}active{% endblock %}
{% block css %}

{% endblock %}
{% block body %}
<div class="row">
		<div class="col-md-3">
		</div> 
		<div class="col-md-8">
			<div class="row">
				<div class="col-md-12">
					<div class="card bg-white">
						<div class="post-new-contain row card-block">
							<div class="col-md-1 col-xs-3 post-profile">
								<img src="{% static '/files/assets/images/user.png' %}" class="img-fluid" alt="">
							</div>
								<form method="POST" class="col-md-11 col-xs-9" action= "{% url 'cmsapp:adminfeedcreate' %}">
									<div class="media">
				
									<div class="media-body">
										<form class="post-form">
										{% csrf_token %}
										{{feedform.post}}
											<div class="text-right m-t-20">
											<button type="submit" class="save btn btn-default btn-primary">Post</button>
											</div>
										
										</form>
									</div>
						</div>
								</form>
					</div>

					</div>
				<div>
					<div class="bg-white p-relative">
						<div class="input-group wall-elips">
							<span class="dropdown-toggle addon-btn text-muted f-right wall-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" role="tooltip"></span>
								<div class="dropdown-menu dropdown-menu-right b-none services-list">
									<a class="dropdown-item" href="#">Remove tag</a>
									<a class="dropdown-item" href="#">Report Photo</a>
									<a class="dropdown-item" href="#">Hide From Timeline</a>
									<a class="dropdown-item" href="#">Blog User</a>
								</div>
						</div>
								{% for feed in feedlist %}
							<div class="card-block">
								<div class="media">
									<div class="media-left media-middle friend-box">
									<a href="#">
									<img class="media-object img-radius m-r-20" src="../files/assets/images/avatar-2.jpg" alt="">
									</a>
									</div>
									<div class="media-body">
										<div class="chat-header">{{feed.created_by}}</div>
										<div class="f-13 text-muted">{{feed.created_at|timesince}} ago</div>
										<!-- <p class="text-muted">{{feed.post}} </p> -->
										<h3>{{feed.post}}</h3>
												<div class="card-block b-b-theme b-t-theme social-msg">
										<a href="#">
										<i class="icofont icofont-heart-alt text-muted">
										</i>
										<span class="b-r-theme">Like (20)</span>
										</a>
										<a href="#">
										<i class="icofont icofont-comment text-muted">
										</i>
										<span class="b-r-theme">Comments (25)</span>
										</a>
										<a href="#">
										<i class="icofont icofont-share text-muted">
										</i>
										<span>Share (10)</span>
										</a>
									</div>
									<div class="card-block user-box">
										<div class="p-b-20">
										<span class="f-14"><a href="#">Comments ({{forloop.counter}})</a>
										</span>
										<span class="f-right">see all comments
										</span>
										 </div>
										 {% for comment in feed.comments.all %}
										<div class="media">
											<a class="media-left" href="#">
											<img class="media-object img-radius m-r-20" src="{% static '/files/assets/images/avatar-1.jpg' %}" alt="Generic placeholder image">
											</a>
											<div class="media-body b-b-theme social-client-description">
											<div class="chat-header">{{comment.comment}}<span class="text-muted">Jane 04, 2015</span></div>
											<p class="text-muted">{{comment.comment_by.username}} </p>
											</div>
										</div>
										{% endfor %}
										<div class="media">
												<a class="media-left" href="#">
												<img class="media-object img-radius m-r-20" src="{% static '/files/assets/images/user.png' %}" alt="Generic placeholder image">
												</a>
												<div class="media-body">
												<form method ="POST" action="{% url 'cmsapp:adminfeedcommentcreate' feed.id %}" >
												<div class="">
													{% csrf_token %}
													{{commentform.comment}}
													<div class="text-right m-t-20">
											<button type="submit" class="save btn btn-default btn-success">Comment</button>
											</div>
												</div>
												</form>
												</div>
											</div>
										</div>
										</div>
									</div>
							</div>
								{% endfor %}
			</div>

			<div class="f-30 text-muted text-center p-30">2014</div>
			</div>
</div>
</div>
</div>
</div>



{% endblock %}

templates/admintemplates/adminleaddelete.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<form class="form" method="POST" action="{% url 'cmsapp:adminleaddelete' object.id %}">{% csrf_token %}

    <div class="modal-body text-center">
        Are you sure you want to delete {{object.title}}?
    </div>
    <div class="modal-footer py-1">
        <button class="btn btn-danger w-50 mx-1">Delete</button>
        <button class="btn btn-default w-50 mx-1" data-dismiss="modal">Cancel</button>
    </div>
</form>

templates/admintemplates/adminleaddetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block body %}
<div style="margin:20px 300px; margin-right: 100px;">
<div class="pcoded-content">
<div class="pcoded-inner-content">

<div class="main-body">
<div class="page-wrapper">

<div class="page-header">
<div class="row align-items-end">
<div class="col-lg-8">
<div class="page-header-title">
<div class="d-inline">
<h4>User Profile</h4>
<span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
</div>
</div>
</div>

</div>
</div>
</div>
</div>
</div>
</div>


<div class="page-body">

<div class="row">
<div class="col-lg-12">
<div class="cover-profile">
 <div class="profile-bg-img">
<img class="profile-bg-img img-fluid" src="{% static 'files/assets/images/user-profile/bg-img1.jpg' %}" alt="bg-img">
<div class="card-block user-info">
<div class="col-md-12">
<div class="media-left">
<a href="#" class="profile-image">
<img class="user-img img-radius" src="{{consultantdetail.image.url}}" alt="user-img" style="width: 100px; height: 100px;">
</a>
</div>
<div class="media-body row">
<div class="col-lg-12">
<div class="user-title">
<h2>{{adminleaddetail.name}}</h2>
</div>
</div>
<div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="row">
<div class="col-lg-12">


<div class="tab-content">

<!-- <div class="tab-pane active" id="personal" role="tabpanel"> -->

<div class="card">
<div class="card-header">
<h5 class="card-header-text">About Me</h5>

</div>
<div class="card-block">
<div class="view-info">
<div class="row">
<div class="col-lg-12">
<div class="general-info">
<div class="row">
<div class="col-lg-12 col-xl-6">
<div class="table-responsive">
<table class="table m-0">
<tbody>
<tr>
<th scope="row">Full Name</th>
<td>{{adminleaddetail.name}}</td>
</tr>
<tr>
<th scope="row">Phone</th>
<td>{{adminleaddetail.phone}}</td>
</tr>
<tr>
<th scope="row">Address</th>
 <td>{{adminleaddetail.address}}</td>
</tr>
<tr>
<th scope="row">Email</th>
<td>{{adminleaddetail.email}}</td>
</tr>

</tbody>
</table>
</div>
</div>
<!-- 
</div> -->

</div>

</div>

</div>

</div>

</div>
<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-header">
<h5 class="card-header-text">Description About Me</h5>

</div>
<div class="card-block user-desc">
<div class="view-desc">
<p>{{consultantdetail.about}}</p>
</div>

{% endblock %}

templates/admintemplates/adminlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block active1 %}active{% endblock %}
{% block css %}

{% endblock %}
{% block body %}


<button class="btn btn-out-dotted btn-info btn-square pull-right" ><a href="{% url 'cmsapp:adminregistration' %}">Add Admin</a></button>
<div class="dt-responsive table-responsive">
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>user</th>
<th>Name</th>
<th>Address</th>
<th>Phone</th>
<th>Email</th>
<th>Action</th>


</tr>
</thead>
<tbody>
    {% for admin in adminlist %}
<tr>
<td>{{admin.user}}</td>
<td> <a href="{% url 'cmsapp:admindetail' admin.id %}">{{admin.name}}</a></td>
<td>{{admin.address}}</td>
<td>{{admin.phone}}</td>
<td>{{admin.email}}</td>
<td><a href="{% url 'cmsapp:adminupdate' admin.id %}" class="btn btn-link btn-info btn-just-icon edit"> 
<i class="material-icons">update</i>
</a></td>



</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
{% endblock %}
{% block js %}



{% endblock %}

templates/admintemplates/adminpasswordchange.html
{% extends 'admintemplates/adminbase.html' %}
{% block body %}
<br>
<form method="POST" class="post-form" style="margin: 20px 500px;">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Submit</button>
    </form>
{% endblock %}

templates/admintemplates/adminstudentlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block active6 %}active{% endblock %}
{% block css %}
{% endblock %}
{% block body %}
<button class="btn btn-out-dotted btn-info btn-square pull-right" ><a href="{% url 'cmsapp:adminstudentregistration' %}">Add Student</a></button>
<div class="dt-responsive table-responsive">
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>S.N</th>
<th>user</th>
<th>name</th>
<th>Address</th>
<th>Phone</th>
<th>Language Course</th>
<th>Assigned to</th>
<th>Actions</th>


</tr>
</thead>
<tbody>
	{% for student in adminstudentlist %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{student.user}}</td>
<td><a href="{% url 'cmsapp:adminstudentdetail' student.id %}">{{student.name}}</a></td>
<td>{{student.address}}</td>
<td>{{student.phone}}</td>
<td>{{student.language_course}}</td>
<td>{{student.assigned_to}}</td>
<td><a href="{% url 'cmsapp:adminstudentupdate' student.id %}" class="btn btn-link btn-info btn-just-icon edit"> 
<i class="material-icons">update</i>
</a>
<a href="{% url 'cmsapp:adminstudentdelete' student.id %}" class="btn btn-link btn-info btn-just-icon delete">
<i class="material-icons">delete</i>
</a></td>

</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

	

templates/admintemplates/admintaskdelete.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<form class="form" method="POST" action="{% url 'cmsapp:admintaskdelete' object.id %}">{% csrf_token %}

    <div class="modal-body text-center">
        Are you sure you want to delete {{object.title}}?
    </div>
    <div class="modal-footer py-1">
        <button class="btn btn-danger w-50 mx-1">Delete</button>
        <button class="btn btn-default w-50 mx-1" data-dismiss="modal">Cancel</button>
    </div>
</form>

templates/admintemplates/adminteacherlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block active4 %}active{% endblock %}
{% block css %}

{% endblock %}
{% block body %}
<button class="btn btn-out-dotted btn-info btn-square pull-right" ><a href="{% url 'cmsapp:adminteacherregistration' %}">Add Teacher</a></button>
<div class="dt-responsive table-responsive">
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>S.N</th>
<th>User</th>
<th>Name</th>
<th>Address</th>
<th>Phone</th>
<th>Qualification</th>
<th>Experience</th>
<th>Teacher</th>


</tr>
</thead>
<tbody>
    {% for teacher in adminteacherlist %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{teacher.user}}</td>
<td><a href="{% url 'cmsapp:adminteacherdetail' teacher.id %}">{{teacher.name}}</a></td>
<td>{{teacher.address}}</td>
<td>{{teacher.phone}}</td>
<td>{{teacher.qualification}}</td>
<td>{{teacher.experience}}</td>
<td><a href="{% url 'cmsapp:adminteacherupdate' teacher.id %}" class="btn btn-link btn-info btn-just-icon edit"> 
<i class="material-icons">update</i>
</a>
<a href="{% url 'cmsapp:adminteacherdelete' teacher.id %}" class="btn btn-link btn-info btn-just-icon delete">
<i class="material-icons">delete</i>
</a></td>

</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

templates/admintemplates/adminvisitordelete.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<form class="form" method="POST" action="{% url 'cmsapp:adminvisitordelete' object.id %}">{% csrf_token %}

    <div class="modal-body text-center">
        Are you sure you want to delete {{object.title}}?
    </div>
    <div class="modal-footer py-1">
        <button class="btn btn-danger w-50 mx-1">Delete</button>
        <button class="btn btn-default w-50 mx-1" data-dismiss="modal">Cancel</button>
    </div>
</form>