cmsapp/urls.py
from django.urls import path, include
from .views import *
from .models import *
app_name = 'cmsapp'


urlpatterns = [

    # Bachelor Pass nabhako bharabhuri haru ko lagi

    path('receptionist/registration/', ReceptionistRegistrationView.as_view(),
         name='receptionistregistration'),
    path('student/registration/', StudentRegistrationView.as_view(),
         name='studentregistration'),
    path('teacher/registration/', TeacherRegistrationView.as_view(),
         name='teacherregistration'),
    path('consultant/registration/', ConsultantRegistrationView.as_view(),
         name='consultantregistration'),
    path('lead/registration/', LeadRegistrationView.as_view(),
         name='leadregistration'),
    path('visitor/registration/', VisitorRegistrationView.as_view(),
         name='visitorregistration'),
    path('admin/registration/', AdminRegistrationView.as_view(),
         name='adminregistration'),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # admin panel urls

    path('adminpanel/', AdminPanelView.as_view(), name='adminpanel'),
    path('admin/list/', AdminListView.as_view(), name='adminlist'),
    path('adminconsultant/list/', AdminConsultantListView.as_view(),
         name='adminconsultantlist'),
    path('adminlead/list/', AdminLeadListView.as_view(),
         name='adminleadlist'),
    path('adminteacher/list/', AdminTeacherListView.as_view(),
         name='adminteacherlist'),
    path('adminreceptionist/list/', AdminReceptionistListView.as_view(),
         name='adminreceptionistlist'),
    path('adminstudent/list/', AdminStudentListView.as_view(),
         name='adminstudentlist'),
    path('adminvisitor/list/', AdminVisitorListView.as_view(),
         name='adminvisitorlist'),
    path('admintask/list/', AdminTaskListView.as_view(),
         name='admintasklist'),
    path('adminappointment/list/', AdminAppointmentListView.as_view(),
         name='adminappointmentlist'),
    path('adminfeed/list/', AdminFeedListView.as_view(),
         name='adminfeedlist'),

    # adminpanel feed create views

    path('adminfeed/create/', AdminFeedCreateView.as_view(), name='adminfeedcreate'),
    path('adminfeed/<int:pk>/comment/create/',
         AdminFeedCommentCreateView.as_view(), name='adminfeedcommentcreate'),
    path('adminfeed/<int:pk>/delete/',
         AdminFeedDeleteView.as_view(), name='adminfeeddelete'),
    path('adminfeed/<int:pk1>/comment/<int:pk2>/delete/',
         AdminFeedCommentDeleteView.as_view(), name='adminfeedcommentdelete'),

    # adminpanel detail views urls

    path('admin/<int:pk>/detail/',
         AdminDetailView.as_view(), name='admindetail'),
    path('adminconsultant/<int:pk>/detail/',
         AdminConsultantDetailView.as_view(), name='adminconsultantdetail'),
    path('adminreceptionist/<int:pk>/detail/',
         AdminReceptionistDetailView.as_view(), name='adminreceptionistdetail'),
    path('student/<int:pk>/detail/',
         AdminStudentDetailView.as_view(), name='adminstudentdetail'),
    path('adminlead/<int:pk>/detail/',
         AdminLeadDetailView.as_view(), name='adminleaddetail'),
    path('adminteacher/<int:pk>/detail/',
         AdminTeacherDetailView.as_view(), name='adminteacherdetail'),

    # admin create views urls
    path('adminteacher/registration/', AdminTeacherRegistrationView.as_view(),
         name='adminteacherregistration'),
    path('adminreceptionist/registration/', AdminReceptionistRegistrationView.as_view(),
         name='adminreceptionistregistration'),
    path('adminstudent/registration/', AdminStudentRegistrationView.as_view(),
         name='adminstudentregistration'),
    path('admintask/create/', AdminTaskCreateView.as_view(),
         name='admintaskcreate'),

    # adminpanel update views urls
    path('consultant/<int:pk>/update', ConsultantUpdateView.as_view(),
         name='consultantupdate'),
    path('admin/<int:pk>/update', AdminUpdateView.as_view(), name='adminupdate'),
    path('adminlead/<int:pk>/update', LeadUpdateView.as_view(),
         name='adminleadupdate'),
    path('adminteacher/<int:pk>/update', AdminTeacherUpdateView.as_view(),
         name='adminteacherupdate'),
    path('adminreceptionist/<int:pk>/update', AdminReceptionistUpdateView.as_view(),
         name='adminreceptionistupdate'),
    path('adminstudent/<int:pk>/update', AdminStudentUpdateView.as_view(),
         name='adminstudentupdate'),

    # adminpanel delete views url
    path('adminconsultant/<int:pk>/delete',
         AdminConsultantDeleteView.as_view(), name='adminconsultantdelete'),
    path('adminlead/<int:pk>/delete',
         AdminLeadDeleteView.as_view(), name='adminleaddelete'),
    path('adminteacher/<int:pk>/delete',
         AdminTeacherDeleteView.as_view(), name='adminteacherdelete'),
    path('adminreceptionist/<int:pk>/delete',
         AdminReceptionistDeleteView.as_view(), name='adminreceptionistdelete'),
    path('adminstudent/<int:pk>/delete',
         AdminStudentDeleteView.as_view(), name='adminstudentdelete'),
    path('adminvisitor/<int:pk>/delete',
         AdminVisitorDeleteView.as_view(), name='adminvisitordelete'),
    path('admintask/<int:pk>/delete',
         AdminTaskDeleteView.as_view(), name='admintaskdelete'),





    # student panel urls

    path('studentpanel/', StudentPanelView.as_view(), name='studentpanel'),
    path('studentteacher/list/', StudentTeacherListView.as_view(),
         name='studentteacherlist'),
    path('studentreceptionist/list/', StudentReceptionistListView.as_view(),
         name='studentreceptionistlist'),

    # studentpanel details urls

    path('student/<int:pk>/detail/',
         StudentDetailView.as_view(), name='studentdetail'),

    # studentpanel feed create views

    path('studentfeed/create/', StudentFeedCreateView.as_view(),
         name='studentfeedcreate'),
    path('studentfeed/<int:pk>/comment/create/',
         StudentFeedCommentCreateView.as_view(), name='studentfeedcommentcreate'),
    path('studentfeed/<int:pk>/delete/',
         StudentFeedDeleteView.as_view(), name='studentfeeddelete'),
    path('studentfeed/<int:pk1>/comment/<int:pk2>/delete/',
         StudentFeedCommentDeleteView.as_view(), name='studentfeedcommentdelete'),


    # teacher panel urls

    path('teacherpanel/', TeacherPanelView.as_view(), name='teacherpanel'),
    path('teacherconsultant/list/', TeacherConsultantListView.as_view(),
         name='teacherconsultantlist'),
    path('teacher/list/', TeacherListView.as_view(),
         name='teacherlist'),
    path('teacherreceptionist/list/', TeacherReceptionistListView.as_view(),
         name='teacherreceptionistlist'),
    path('teacherstudent/list/', TeacherStudentListView.as_view(),
         name='teacherstudentlist'),
    path('teachertask/list/', TeacherTaskListView.as_view(),
         name='teachertasklist'),
    path('teacheruniversity/list/', TeacherUniversityListView.as_view(),
         name='teacheruniversitylist'),
    path('teacherfeed/list/', TeacherFeedListView.as_view(), name='teacherfeedlist'),
    path('teacherstudymaterials/list/',
         TeacherStudyMaterialsListView.as_view(), name='teacherstudymaterialslist'),

    # teacherpanel feed create views

    path('teacherfeed/create/', TeacherFeedCreateView.as_view(),
         name='teacherfeedcreate'),
    path('teacherfeed/<int:pk>/comment/create/',
         TeacherFeedCommentCreateView.as_view(), name='teacherfeedcommentcreate'),
    path('teacherfeed/<int:pk>/delete/',
         TeacherFeedDeleteView.as_view(), name='teacherfeeddelete'),
    path('teacherfeed/<int:pk1>/comment/<int:pk2>/delete/',
         TeacherFeedCommentDeleteView.as_view(), name='teacherfeedcommentdelete'),


    # teacherpanel details views urls

    path('teacher/<int:pk>/detail/',
         TeacherDetailView.as_view(), name='teacherdetail'),
    path('teacherstudent/<int:pk>/detail/',
         TeacherStudentDetailView.as_view(), name='teacherstudentdetail'),

    # teacherpanel create views urls

    path('teacherstudymaterials/create/',
         TeacherStudyMaterialsCreateView.as_view(), name='teacherstudymaterialscreate'),

    # teacherpanel update views urls
    path('teacherstudymaterials/<int:pk>/update/',
         TeacherStudyMaterialsUpdateView.as_view(), name='teacherstudymaterialsupdate'),

    # teacherpanel delete views urls
    path('teacherstudymaterials/<int:pk>/delete/',
         TeacherStudyMaterialsDeleteView.as_view(), name='teacherstudymaterialsdelete'),

    # consultant panel urls

    path('consultantpanel/', ConsultantPanelView.as_view(), name='consultantpanel'),
    path('consultant/list/', ConsultantListView.as_view(),
         name='consultantlist'),
    path('consultantlead/list/', ConsultantLeadListView.as_view(),
         name='consultantleadlist'),
    path('consultantteacher/list/', ConsultantTeacherListView.as_view(),
         name='consultantteacherlist'),
    path('consultantreceptionist/list/', ConsultantReceptionistListView.as_view(),
         name='consultantreceptionistlist'),
    path('consultantstudent/list/', ConsultantStudentListView.as_view(),
         name='consultantstudentlist'),
    path('consultantvisitor/list/', ConsultantVisitorListView.as_view(),
         name='consultantvisitorlist'),
    path('consultanttask/list/', ConsultantTaskListView.as_view(),
         name='consultanttasklist'),
    path('consultantappointment/list/', ConsultantAppointmentListView.as_view(),
         name='consultantappointmentlist'),
    path('consultantfeed/list/', ConsultantFeedListView.as_view(),
         name='consultantfeedlist'),
    path('consultantdocument/create/', ConsultantDocumentCreateView.as_view(),
         name='consultantdocumentcreate'),

    # consultant create view urls
    path('consultanttask/create/', ConsultantTaskCreateView.as_view(),
         name='consultanttaskcreate'),
    path('consultantappointment/create/', ConsultantAppointmentCreateView.as_view(),

cmsproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmsapp.urls', namespace='cmsapp')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/consultanttemplates/consultantappointmentlist.html
{% extends 'consultanttemplates/consultantbase.html' %}
{% load static %}
{% block active8 %}active{% endblock %}
{% block css %}


{% endblock %}
{% block body %}



<div class="main-body">
<div class="page-wrapper">

<div class="page-header">
<div class="row align-items-end">
<div class="col-lg-8">
<div class="page-header-title">
<div class="d-inline">
<h4>Task List1</h4>
<span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
</div>
</div>
</div>
<div class="col-lg-4">
<div class="page-header-breadcrumb">
<ul class="breadcrumb-title">
<li class="breadcrumb-item">
<a href="index.html"> <i class="feather icon-home"></i> </a>
</li>
<li class="breadcrumb-item"><a href="#!">Appointment</a>
</li>
<li class="breadcrumb-item"><a href="#!">Appointment list</a>
</li>
</ul>
</div>
</div>
</div>
</div>



<div class="row">
<div class="col-sm-12">

<div class="card">
<div class="card-header col-md-10">
<h5>Task List</h5>
<button class="btn btn-out-dotted btn-info btn-square pull-right" ><a href="{% url 'cmsapp:consultantappointmentcreate' %}">Add Appointment</a></button>
</div>
<div class="card-block task-list">
<div class="table-responsive">
<table id="datatables" class="table dt-responsive task-list-table table-striped table-bordered nowrap">
<thead>
<tr>
<th>S.N.</th>
<th>Name</th>
<th>Phone</th>
<th>Subject</th>
<th>Party2</th>
<th>Date</th>
<th class="text-right">Action</th>
</tr>
</thead>
<tfoot>
        <tr>
            <th>S.N.</th>
			<th>Name</th>
			<th>Phone</th>
			<th>Subject</th>
			<th>Party2</th>
			<th>Date</th>
			<th class="text-right">Action</th>
        </tr>
    </tfoot>
<tbody class="task-page">
{% for appointment in consultantappointmentlist %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{appointment.party1}}</td>
<td>{{appointment.phone}}</td>
<td>{{appointment.subject}}</td>
<td>{{appointment.party2}}</td>
<td>{{appointment.date}}</td>
<td>
<a href="{% url 'cmsapp:consultantappointmentupdate' appointment.id %}" class="btn btn-link btn-info btn-just-icon edit"> 
<i class="material-icons">update</i>
</a>
<!-- <a data-remote="{% url 'cmsapp:consultantappointmentdelete' appointment.id %}" data-toggle="modal" data-target="#clinic-modal" href="{% url 'cmsapp:appointmentdelete' appointment.id %}" class="btn btn-link btn-info btn-just-icon delete">
<i class="material-icons">delete</i>
</a> -->

</td> 
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
</div>




</div>





{% endblock %}

{% block js %}




{% endblock %}

templates/consultanttemplates/consultantcreate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />  
<head>
    <title>Consultant Registration</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="#">
    <meta name="keywords" content="Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="#">

    <link rel="icon" href="https://colorlib.com/polygon/adminty/files/assets/images/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'files/bower_components/bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'files/assets/icon/themify-icons/themify-icons.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'files/assets/icon/icofont/css/icofont.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'files/assets/css/style.css' %}">
</head>
<body class="fix-menu">

    <div class="theme-loader">
    <div class="ball-scale">
    <div class='contain'>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    </div>
    </div>
    </div>

    <section class="login-block">

    <div class="container">
    <div class="row">
    <div class="col-sm-12">

    <form class="md-float-material post-form form-material" method="POST" >
    {% csrf_token %}
    <div class="text-center">
    <img src="{% static 'files/assets/images/logo.png' %}" alt="logo.png">
    </div>
    <div class="auth-box card">
    <div class="card-block">
    <div class="row m-b-20">
    <div class="col-md-12">
    <h3 class="text-center txt-primary">Consultant Registration</h3>
    </div>
    </div>
    <div class="form-group form-primary">
    {{form.username}}
    <span class="form-bar"></span>
    </div>
    <div class="form-group form-primary">
    {{form.email}}
    <span class="form-bar"></span>
    </div>
    <div class="row">
    <div class="col-sm-6">
     <div class="form-group form-primary">
    {{form.password1}}
    <span class="form-bar"></span>
    </div>
    </div>
    <div class="col-sm-6">
    <div class="form-group form-primary">
    {{form.password2}}
    <span class="form-bar"></span>
    </div>
    </div>
    </div>
    <div class="form-group form-primary">
    {{form.name}}
    <span class="form-bar"></span>
    </div>
    <div class="form-group form-primary">
    {{form.phone}}
    <span class="form-bar"></span>
    </div>
    <div class="form-group form-primary">
    {{form.address}}
    <span class="form-bar"></span>
    </div>
    <div class="row m-t-30">
    <div class="col-md-12">
    <button type="submit" class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20">Register</button>
    </div>
    </div>
    <div class="row">
    <div class="col-md-10">
    <p class="text-inverse text-left m-b-0">Thank you.</p>
    <p class="text-inverse text-left"><a href="index.html"><b class="f-w-600">Back to website</b></a></p>
    </div>
    <div class="col-md-2">
    <img src="{% static 'files/assets/images/auth/Logo-small-bottom.png' %}" alt="small-logo.png">
    </div>
    </div>
    </div>
    </div>
    </form>

    </div>

    </div>

    </div>

    </section>



    <script type="text/javascript" src="{% static 'files/bower_components/jquery/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/jquery-ui/js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/popper.js' %}/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/bootstrap/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'files/bower_components/jquery-slimscroll/js/jquery.slimscroll.js' %}"></script>

    <script type="text/javascript" src="{% static 'files/bower_components/modernizr/js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/modernizr/js/css-scrollbars.js' %}"></script>

    <script type="text/javascript" src="{% static 'files/bower_components/i18next/js/i18next.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/i18next-xhr-backend/js/i18nextXHRBackend.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/i18next-browser-languagedetector/js/i18nextBrowserLanguageDetector.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/jquery-i18next/js/jquery-i18next.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/assets/js/common-pages.js' %}"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-23581568-13');
    </script>
</body>
</html>

templates/consultanttemplates/consultantdetail.html
{% extends 'consultanttemplates/consultantbase.html' %}
{% load static %}
{% block body %}
<div>
<div class="pcoded-content">
<div class="pcoded-inner-content">

<div class="main-body">
<div class="page-wrapper">

<div class="page-header">
<div class="row align-items-end">
<div class="col-lg-8">
<div class="page-header-title">
<div class="d-inline">
<h4>User Profile</h4>
<span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>

</div>
</div>
</div>

</div>
</div>
</div>
</div>
</div>
</div>


<div class="page-body">

<div class="row">
<div class="col-lg-12">
<div class="cover-profile">
 <div class="profile-bg-img">
<img class="profile-bg-img img-fluid" src="{% static 'files/assets/images/user-profile/bg-img1.jpg' %}" alt="bg-img">
<div class="card-block user-info">
<div class="col-md-12">
<div class="media-left">
<a href="#" class="profile-image">
<img class="user-img img-radius" src="{{consultantdetail.image.url}}" alt="user-img" style="width: 100px; height: 100px;">
</a>
</div>
<div class="media-body row">
<div class="col-lg-12">
<div class="user-title">
<h2>{{consultantdetail.name}}</h2>
</div>
</div>
<div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="row">
<div class="col-lg-12">


<div class="tab-content">

<!-- <div class="tab-pane active" id="personal" role="tabpanel"> -->

<div class="card">
<div class="card-header">
<h5 class="card-header-text">About Me</h5>

</div>
<div class="card-block">
<div class="view-info">
<div class="row">
<div class="col-lg-12">
<div class="general-info">
<div class="row">
<div class="col-lg-12 col-xl-6">
<div class="table-responsive">
<table class="table m-0">
<tbody>
<tr>
<th scope="row">Full Name</th>
<td>{{consultantdetail.name}}</td>
</tr>
<tr>
<th scope="row">Phone</th>
<td>{{consultantdetail.phone}}</td>
</tr>
<tr>
<th scope="row">Address</th>
 <td>{{consultantdetail.address}}</td>
</tr>
<tr>
<th scope="row">Email</th>
<td>{{consultantdetail.email}}</td>
</tr>
<tr>
	

</tr>

</tbody>
</table>
</div>
</div>

</div>

</div>

</div>

</div>

</div>
<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-header">
<h5 class="card-header-text">Description About Me</h5>

</div>
<div class="card-block user-desc">
<div class="view-desc">
<p>{{consultantdetail.about}}</p>
</div>

{% endblock %}

templates/consultanttemplates/consultantleadlist.html
{% extends 'consultanttemplates/consultantbase.html' %}
{% load static %}
{% block active2 %} active {% endblock %}
{% block css %}

{% endblock %}
{% block body %}
<div class="card-block" >
<div class="dt-responsive table-responsive">
<div class="card-header col-md-12">
<h5>Lead List</h5>
<button class="btn btn-out-dotted btn-info btn-square pull-right" ><a href="{% url 'cmsapp:leadregistration' %}">Add Lead</a></button>
</div>
<br>
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>S.N</th>
<th>user</th>
<th>Name</th>
<th>Address</th>
<th>Phone</th>
<th>Email</th>
<th>Visa Status</th>



</tr>
</thead>
<tbody>
    {% for lead in consultantleadlist %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{lead.user}}</td>
<td><a href="{% url 'cmsapp:consultantleaddetail' lead.id %}">{{lead.name}}</a></td>
<td>{{lead.address}}</td>
<td>{{lead.phone}}</td>
<td>{{lead.email}}</td>
<td>{{lead.visa_status}}</td>


</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

templates/consultanttemplates/consultantlist.html
{% extends 'consultanttemplates/consultantbase.html' %}
{% load static %}
{% block active1 %} active {% endblock %}
{% block css %}

{% endblock %}
{% block body %}
<div class="card-block">
<div class="dt-responsive table-responsive">
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>user</th>
<th>Name</th>
<th>Address</th>
<th>Phone</th>
<th>Email</th>

</tr>
</thead>
<tbody>
    {% for consultant in consultantlist %}
<tr>
<td>{{consultant.user}}</td>
<td><a href="{% url 'cmsapp:consultantdetail' consultant.id %}">{{consultant.name}}</a></td>
<td>{{consultant.address}}</td>
<td>{{consultant.phone}}</td>
<td>{{consultant.email}}</td>

</tr>
{% endfor %}
</tbody>

</table>
</div>
</div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

templates/consultanttemplates/consultantpanel.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Consultant</h1>
<h1><a href="{% url 'cmsapp:passwordchange' %}">Password Change</a><br><br></h1>
<h1><a href="{% url 'cmsapp:logout' %}">Logout</a><br><br></h1>
</body>
</html>

templates/consultanttemplates/consultanttasklist.html
{% extends 'consultanttemplates/consultantbase.html' %}
{% load static %}
{% block active7 %}active{% endblock %}
{% block css %}


{% endblock %}
{% block body %}


<div class="theme-loader">
<div class="ball-scale">
<div class='contain'>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
<div class="ring">
<div class="frame"></div>
</div>
</div>
</div>
</div>

<!-- <div class="pcoded-content">
<div class="pcoded-inner-content"> -->

<div class="main-body">


<div class="page-header">
<div class="row align-items-end">
<div class="col-lg-8">
<div class="page-header-title">
<div class="d-inline">
<h4>Task List1</h4>
<span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
</div>
</div>
</div>
<div class="col-lg-4">
<div class="page-header-breadcrumb">
<ul class="breadcrumb-title">
<li class="breadcrumb-item">
<a href="index.html"> <i class="feather icon-home"></i> </a>
</li>
<li class="breadcrumb-item"><a href="#!">Task</a>
</li>
<li class="breadcrumb-item"><a href="#!">Task list</a>
</li>
</ul>
</div>
</div>
</div>
</div>



<div class="row">
<div class="col-sm-12">

<div class="card">
<div class="card-header col-md-10">
<h5>Task List</h5>
<button class="btn btn-out-dotted btn-info btn-square pull-right" ><a href="{% url 'cmsapp:consultanttaskcreate' %}">Add task</a></button>
</div>
<div class="card-block task-list">
<div class="table-responsive">
<table id="datatables" class="table dt-responsive task-list-table table-striped table-bordered nowrap">
<thead>
<tr>
<th>S.N.</th>
<th>Task title</th>
<th>Task Description</th>
<th>Status</th>
<th>Priority</th>
<th>Due Date</th>
<th>Assigned to</th>
<th class="text-right">Action</th>
</tr>
</thead>
<tfoot>
        <tr>
            <th>S.N.</th>
			<th>Task title</th>
			<th>Task Description</th>
			<th>Status</th>
			<th>Priority</th>
			<th>Due Date</th>
			<th>Assigned to</th>
			<th class="text-right">Action</th>
        </tr>
    </tfoot>
<tbody class="task-page">
{% for task in tasklist %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{task.title}}</td>
<td>{{task.content}}</td>
<td>{{task.status}}</td>
<td>{{task.priority}}</td>
<td>{{task.due_date}}</td>
<td>{% for user in task.assigned_to.all %}
{{user.username}} 
{% endfor %}</td>
<td>
<a href="{% url 'cmsapp:consultanttaskupdate' task.id %}" class="btn btn-link btn-info btn-just-icon edit"> 
<i class="material-icons">update</i>
</a>
<!-- <a data-remote="{% url 'cmsapp:consultanttaskdelete' task.id %}" data-toggle="modal" data-target="#clinic-modal" href="{% url 'cmsapp:consultanttaskdelete' task.id %}" class="btn btn-link btn-info btn-just-icon delete">
<i class="material-icons">delete</i>
</a> -->

</td> 
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>

</div>
</div>
</div>
</div>

{% endblock %}
{% block js %}



{% endblock %}