cmsapp/urls.py
from django.urls import path, include
from .views import *
from .models import *
app_name = 'cmsapp'


urlpatterns = [

    # Bachelor Pass nabhako bharabhuri haru ko lagi

    path('receptionist/registration/', ReceptionistRegistrationView.as_view(),
         name='receptionistregistration'),
    path('student/registration/', StudentRegistrationView.as_view(),
         name='studentregistration'),
    path('teacher/registration/', TeacherRegistrationView.as_view(),
         name='teacherregistration'),
    path('consultant/registration/', ConsultantRegistrationView.as_view(),
         name='consultantregistration'),
    path('lead/registration/', LeadRegistrationView.as_view(),
         name='leadregistration'),
    path('visitor/registration/', VisitorRegistrationView.as_view(),
         name='visitorregistration'),
    path('admin/registration/', AdminRegistrationView.as_view(),
         name='adminregistration'),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # admin panel urls

    path('adminpanel/', AdminPanelView.as_view(), name='adminpanel'),
    path('admin/list/', AdminListView.as_view(), name='adminlist'),
    path('adminconsultant/list/', AdminConsultantListView.as_view(),
         name='adminconsultantlist'),
    path('adminlead/list/', AdminLeadListView.as_view(),
         name='adminleadlist'),
    path('adminteacher/list/', AdminTeacherListView.as_view(),
         name='adminteacherlist'),
    path('adminreceptionist/list/', AdminReceptionistListView.as_view(),
         name='adminreceptionistlist'),
    path('adminstudent/list/', AdminStudentListView.as_view(),
         name='adminstudentlist'),
    path('adminvisitor/list/', AdminVisitorListView.as_view(),
         name='adminvisitorlist'),
    path('admintask/list/', AdminTaskListView.as_view(),
         name='admintasklist'),
    path('adminappointment/list/', AdminAppointmentListView.as_view(),
         name='adminappointmentlist'),
    path('adminfeed/list/', AdminFeedListView.as_view(),
         name='adminfeedlist'),

    # adminpanel feed create views

    path('adminfeed/create/', AdminFeedCreateView.as_view(), name='adminfeedcreate'),
    path('adminfeed/<int:pk>/comment/create/',
         AdminFeedCommentCreateView.as_view(), name='adminfeedcommentcreate'),
    path('adminfeed/<int:pk>/delete/',
         AdminFeedDeleteView.as_view(), name='adminfeeddelete'),
    path('adminfeed/<int:pk1>/comment/<int:pk2>/delete/',
         AdminFeedCommentDeleteView.as_view(), name='adminfeedcommentdelete'),

    # adminpanel detail views urls

    path('admin/<int:pk>/detail/',
         AdminDetailView.as_view(), name='admindetail'),
    path('adminconsultant/<int:pk>/detail/',
         AdminConsultantDetailView.as_view(), name='adminconsultantdetail'),
    path('adminreceptionist/<int:pk>/detail/',
         AdminReceptionistDetailView.as_view(), name='adminreceptionistdetail'),
    path('student/<int:pk>/detail/',
         AdminStudentDetailView.as_view(), name='adminstudentdetail'),
    path('adminlead/<int:pk>/detail/',
         AdminLeadDetailView.as_view(), name='adminleaddetail'),
    path('adminteacher/<int:pk>/detail/',
         AdminTeacherDetailView.as_view(), name='adminteacherdetail'),

    # admin create views urls
    path('adminteacher/registration/', AdminTeacherRegistrationView.as_view(),
         name='adminteacherregistration'),
    path('adminreceptionist/registration/', AdminReceptionistRegistrationView.as_view(),
         name='adminreceptionistregistration'),
    path('adminstudent/registration/', AdminStudentRegistrationView.as_view(),
         name='adminstudentregistration'),
    path('admintask/create/', AdminTaskCreateView.as_view(),
         name='admintaskcreate'),

    # adminpanel update views urls
    path('consultant/<int:pk>/update', ConsultantUpdateView.as_view(),
         name='consultantupdate'),
    path('admin/<int:pk>/update', AdminUpdateView.as_view(), name='adminupdate'),
    path('adminlead/<int:pk>/update', LeadUpdateView.as_view(),
         name='adminleadupdate'),
    path('adminteacher/<int:pk>/update', AdminTeacherUpdateView.as_view(),
         name='adminteacherupdate'),
    path('adminreceptionist/<int:pk>/update', AdminReceptionistUpdateView.as_view(),
         name='adminreceptionistupdate'),
    path('adminstudent/<int:pk>/update', AdminStudentUpdateView.as_view(),
         name='adminstudentupdate'),

    # adminpanel delete views url
    path('adminconsultant/<int:pk>/delete',
         AdminConsultantDeleteView.as_view(), name='adminconsultantdelete'),
    path('adminlead/<int:pk>/delete',
         AdminLeadDeleteView.as_view(), name='adminleaddelete'),
    path('adminteacher/<int:pk>/delete',
         AdminTeacherDeleteView.as_view(), name='adminteacherdelete'),
    path('adminreceptionist/<int:pk>/delete',
         AdminReceptionistDeleteView.as_view(), name='adminreceptionistdelete'),
    path('adminstudent/<int:pk>/delete',
         AdminStudentDeleteView.as_view(), name='adminstudentdelete'),
    path('adminvisitor/<int:pk>/delete',
         AdminVisitorDeleteView.as_view(), name='adminvisitordelete'),
    path('admintask/<int:pk>/delete',
         AdminTaskDeleteView.as_view(), name='admintaskdelete'),





    # student panel urls

    path('studentpanel/', StudentPanelView.as_view(), name='studentpanel'),
    path('studentteacher/list/', StudentTeacherListView.as_view(),
         name='studentteacherlist'),
    path('studentreceptionist/list/', StudentReceptionistListView.as_view(),
         name='studentreceptionistlist'),

    # studentpanel details urls

    path('student/<int:pk>/detail/',
         StudentDetailView.as_view(), name='studentdetail'),

    # studentpanel feed create views

    path('studentfeed/create/', StudentFeedCreateView.as_view(),
         name='studentfeedcreate'),
    path('studentfeed/<int:pk>/comment/create/',
         StudentFeedCommentCreateView.as_view(), name='studentfeedcommentcreate'),
    path('studentfeed/<int:pk>/delete/',
         StudentFeedDeleteView.as_view(), name='studentfeeddelete'),
    path('studentfeed/<int:pk1>/comment/<int:pk2>/delete/',
         StudentFeedCommentDeleteView.as_view(), name='studentfeedcommentdelete'),


    # teacher panel urls

    path('teacherpanel/', TeacherPanelView.as_view(), name='teacherpanel'),
    path('teacherconsultant/list/', TeacherConsultantListView.as_view(),
         name='teacherconsultantlist'),
    path('teacher/list/', TeacherListView.as_view(),
         name='teacherlist'),
    path('teacherreceptionist/list/', TeacherReceptionistListView.as_view(),
         name='teacherreceptionistlist'),
    path('teacherstudent/list/', TeacherStudentListView.as_view(),
         name='teacherstudentlist'),
    path('teachertask/list/', TeacherTaskListView.as_view(),
         name='teachertasklist'),
    path('teacheruniversity/list/', TeacherUniversityListView.as_view(),
         name='teacheruniversitylist'),
    path('teacherfeed/list/', TeacherFeedListView.as_view(), name='teacherfeedlist'),
    path('teacherstudymaterials/list/',
         TeacherStudyMaterialsListView.as_view(), name='teacherstudymaterialslist'),

    # teacherpanel feed create views

    path('teacherfeed/create/', TeacherFeedCreateView.as_view(),
         name='teacherfeedcreate'),
    path('teacherfeed/<int:pk>/comment/create/',
         TeacherFeedCommentCreateView.as_view(), name='teacherfeedcommentcreate'),
    path('teacherfeed/<int:pk>/delete/',
         TeacherFeedDeleteView.as_view(), name='teacherfeeddelete'),
    path('teacherfeed/<int:pk1>/comment/<int:pk2>/delete/',
         TeacherFeedCommentDeleteView.as_view(), name='teacherfeedcommentdelete'),


    # teacherpanel details views urls

    path('teacher/<int:pk>/detail/',
         TeacherDetailView.as_view(), name='teacherdetail'),
    path('teacherstudent/<int:pk>/detail/',
         TeacherStudentDetailView.as_view(), name='teacherstudentdetail'),

    # teacherpanel create views urls

    path('teacherstudymaterials/create/',
         TeacherStudyMaterialsCreateView.as_view(), name='teacherstudymaterialscreate'),

    # teacherpanel update views urls
    path('teacherstudymaterials/<int:pk>/update/',
         TeacherStudyMaterialsUpdateView.as_view(), name='teacherstudymaterialsupdate'),

    # teacherpanel delete views urls
    path('teacherstudymaterials/<int:pk>/delete/',
         TeacherStudyMaterialsDeleteView.as_view(), name='teacherstudymaterialsdelete'),

    # consultant panel urls

    path('consultantpanel/', ConsultantPanelView.as_view(), name='consultantpanel'),
    path('consultant/list/', ConsultantListView.as_view(),
         name='consultantlist'),
    path('consultantlead/list/', ConsultantLeadListView.as_view(),
         name='consultantleadlist'),
    path('consultantteacher/list/', ConsultantTeacherListView.as_view(),
         name='consultantteacherlist'),
    path('consultantreceptionist/list/', ConsultantReceptionistListView.as_view(),
         name='consultantreceptionistlist'),
    path('consultantstudent/list/', ConsultantStudentListView.as_view(),
         name='consultantstudentlist'),
    path('consultantvisitor/list/', ConsultantVisitorListView.as_view(),
         name='consultantvisitorlist'),
    path('consultanttask/list/', ConsultantTaskListView.as_view(),
         name='consultanttasklist'),
    path('consultantappointment/list/', ConsultantAppointmentListView.as_view(),
         name='consultantappointmentlist'),
    path('consultantfeed/list/', ConsultantFeedListView.as_view(),
         name='consultantfeedlist'),
    path('consultantdocument/create/', ConsultantDocumentCreateView.as_view(),
         name='consultantdocumentcreate'),

    # consultant create view urls
    path('consultanttask/create/', ConsultantTaskCreateView.as_view(),
         name='consultanttaskcreate'),
    path('consultantappointment/create/', ConsultantAppointmentCreateView.as_view(),

cmsproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmsapp.urls', namespace='cmsapp')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


templates/studenttemplates/studentcreate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />  
<head>
    <title>Student Registration</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="#">
    <meta name="keywords" content="Admin , Responsive, Landing, Bootstrap, App, Template, Mobile, iOS, Android, apple, creative app">
    <meta name="author" content="#">

    <link rel="icon" href="https://colorlib.com/polygon/adminty/files/assets/images/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'files/bower_components/bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'files/assets/icon/themify-icons/themify-icons.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'files/assets/icon/icofont/css/icofont.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'files/assets/css/style.css' %}">
</head>
<body class="fix-menu">

    <div class="theme-loader">
    <div class="ball-scale">
    <div class='contain'>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    <div class="ring"><div class="frame"></div></div>
    </div>
    </div>
    </div>

    <section class="login-block">

    <div class="container">
    <div class="row">
    <div class="col-sm-12">

    <form class="md-float-material post-form form-material" method="POST" >
    {% csrf_token %}
    <div class="text-center">
    <img src="{% static 'files/assets/images/logo.png' %}" alt="logo.png">
    </div>
    <div class="auth-box card">
    <div class="card-block">
    <div class="row m-b-20">
    <div class="col-md-12">
    <h3 class="text-center txt-primary">Student Registration</h3>
    </div>
    </div>
    {% if form.errors %}
        {% for username in form %}
            {% for error in username.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="form-group form-primary">
    {{form.username}}
    <span class="form-bar"></span>
    </div>
    <div class="row">
    <div class="col-sm-6">
     <div class="form-group form-primary">
    {{form.password1}}
    <span class="form-bar"></span>
    </div>
    </div>
    <div class="col-sm-6">
    <div class="form-group form-primary">
    {{form.password2}}
    <span class="form-bar"></span>
    </div>
    </div>
    </div>
    <div class="form-group form-primary">
    {{form.name}}
    <span class="form-bar"></span>
    </div>
    <div class="form-group form-primary">
    {{form.email}}
    <span class="form-bar"></span>
    </div>
    <div class="form-group form-primary">
    {{form.phone}}
    <span class="form-bar"></span>
    </div>
    <div class="form-group form-primary">
    {{form.address}}
    <span class="form-bar"></span>
    </div>
    <div class="form-group form-primary">
    {{form.language_course}}
    <span class="form-bar"></span>
    </div>
    <div class="row m-t-30">
    <div class="col-md-12">
    <button type="submit" class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20">Register</button>
    </div>
    </div>
    <div class="row">
    <div class="col-md-10">
    <p class="text-inverse text-left m-b-0">Thank you.</p>
    <p class="text-inverse text-left"><a href="index.html"><b class="f-w-600">Back to website</b></a></p>
    </div>
    <div class="col-md-2">
    <img src="{% static 'files/assets/images/auth/Logo-small-bottom.png' %}" alt="small-logo.png">
    </div>
    </div>
    </div>
    </div>
    </form>

    </div>

    </div>

    </div>

    </section>




    <script type="text/javascript" src="{% static 'files/bower_components/jquery/js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/jquery-ui/js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/popper.js' %}/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/bootstrap/js/bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'files/bower_components/jquery-slimscroll/js/jquery.slimscroll.js' %}"></script>

    <script type="text/javascript" src="{% static 'files/bower_components/modernizr/js/modernizr.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/modernizr/js/css-scrollbars.js' %}"></script>

    <script type="text/javascript" src="{% static 'files/bower_components/i18next/js/i18next.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/i18next-xhr-backend/js/i18nextXHRBackend.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/i18next-browser-languagedetector/js/i18nextBrowserLanguageDetector.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/bower_components/jquery-i18next/js/jquery-i18next.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'files/assets/js/common-pages.js' %}"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-23581568-13');
    </script>
</body>
</html>

templates/studenttemplates/studentdetail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div style="margin:20px 300px; margin-right: 100px;">
<div class="pcoded-content">
<div class="pcoded-inner-content">

<div class="main-body">
<div class="page-wrapper">

<div class="page-header">
<div class="row align-items-end">
<div class="col-lg-8">
<div class="page-header-title">
<div class="d-inline">
<h4>User Profile</h4>
<span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span>
</div>
</div>
</div>

</div>
</div>
</div>
</div>
</div>
</div>


<div class="page-body">

<div class="row">
<div class="col-lg-12">
<div class="cover-profile">
 <div class="profile-bg-img">
<img class="profile-bg-img img-fluid" src="{% static 'files/assets/images/user-profile/bg-img1.jpg' %}" alt="bg-img">
<div class="card-block user-info">
<div class="col-md-12">
<div class="media-left">
<a href="#" class="profile-image">
<img class="user-img img-radius" src="{{studentdetail.image.url}}" alt="user-img" style="width: 100px; height: 100px;">
</a>
</div>
<div class="media-body row">
<div class="col-lg-12">
<div class="user-title">
<h2>{{studentdetail.name}}</h2>
</div>
</div>
<div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

<div class="row">
<div class="col-lg-12">


<div class="tab-content">

<!-- <div class="tab-pane active" id="personal" role="tabpanel"> -->

<div class="card">
<div class="card-header">
<h5 class="card-header-text">About Me</h5>

</div>
<div class="card-block">
<div class="view-info">
<div class="row">
<div class="col-lg-12">
<div class="general-info">
<div class="row">
<div class="col-lg-12 col-xl-8">
<div class="table-responsive">
<table class="table m-0">
<tbody>
<tr>
<th scope="row">Full Name</th>
<td>{{studentdetail.name}}</td>
</tr>
<tr>
<th scope="row">Phone</th>
<td>{{studentdetail.phone}}</td>
</tr>
<tr>
<th scope="row">Address</th>
 <td>{{studentdetail.address}}</td>
</tr>
<tr>
<th scope="row">Email</th>
<td>{{studentdetail.email}}</td>
</tr>
<tr>
<th scope="row">Assigned to</th>
<td>{{studentdetail.assigned_to}}</td>
</tr>
<tr>
<th scope="row">Language Course</th>
<td>{{studentdetail.language_course}}</td>
</tr>


</tbody>
</table>
</div>
</div>
<!-- 
</div> -->

</div>

</div>

</div>

</div>

</div>
<div class="row">
<div class="col-lg-12">
<div class="card">
<div class="card-header">
<h5 class="card-header-text">Description About Me</h5>

</div>
<div class="card-block user-desc">
<div class="view-desc">
<p>{{studentdetail.about}}</p>
</div>

{% endblock %}

templates/studenttemplates/studentlist.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'files/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'files/assets/pages/data-table/css/buttons.dataTables.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'files/bower_components/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}">
{% endblock %}
{% block body %}
<!-- <h4>LanguageCourses</h4>
	{% for course in languagecourselist %}
	<h4><li style="margin:20px 600px;">{{course.title}}</li></h4>
	<p style="margin:20px 600px;"> fee==={{course.fee}}</p>
	<p style="margin:20px 600px;"> schedule==={{course.schedule}}</p>
	<p style="margin:20px 600px;"> seats==={{course.seats}}</p>
	



{% endfor %} -->
<div class="card-block" style="margin:20px 300px; margin-right: 100px;">
<div class="dt-responsive table-responsive">
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>user</th>
<th>name</th>
<th>Address</th>
<th>Phone</th>
<th>Language Course</th>
<th>Assigned to</th>


</tr>
</thead>
<tbody>
	{% for student in studentlist %}
<tr>
<td>{{student.user}}</td>
<td><a href="{% url 'cmsapp:studentdetail' student.id %}">{{student.name}}</a></td>
<td>{{student.address}}</td>
<td>{{student.phone}}</td>
<td>{{student.language_course}}</td>
<td>{{student.assigned_to}}</td>

</tr>
{% endfor %}
</tbody>
<!-- <tfoot>
<tr>
<th>Name</th>
<th>Position</th>
<th>Office</th>
<th>Age</th>
<th>Start date</th>
<th>Salary</th>
</tr>
</tfoot> -->
</table>
</div>
</div>
</div>
{% endblock %}
{% block js %}
<script src = "https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="{% static 'adminstatic/js/plugins/jquery.datatables.js' %}"></script>
<script src="{% static 'files/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'files/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'files/bower_components/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'files/bower_components/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'files/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'files/bower_components/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'files/bower_components/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'files/assets/pages/data-table/js/data-table-custom.js' %}"></script>
<script src="{% static 'adminstatic/js/plugins/jquery.datatables.js' %}"></script>
<script type="text/javascript">
    window.setTimeout(function() {
    $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove(); 
    });
}, 1000);
</script>
<script type="text/javascript">

$(document).ready(function() {
    $('#datatables').DataTable({
        "pagingType": "full_numbers",
        "lengthMenu": [
            [10, 25, 50, -1],
            [10, 25, 50, "All"]
        ],
        responsive: true,
        language: {
            search: "_INPUT_",
            searchPlaceholder: "Search records",
        }

    $('.card .material-datatables label').addClass('form-group');
});

    });



</script>
{% endblock %}

	

templates/studenttemplates/studentpanel.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<h1>Student</h1>
<h1><a href="{% url 'cmsapp:passwordchange' %}">Password Change</a><br><br></h1>
<h1><a href="{% url 'cmsapp:logout' %}">Logout</a><br><br></h1>
</body>
</html>

templates/studenttemplates/studentpasswordchange.html
{% extends 'studenttemplates/studentbase.html' %}
{% block body %}
<br>
<form method="POST" class="post-form" style="margin: 20px 500px;">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Submit</button>
    </form>
{% endblock %}

templates/studenttemplates/studentreceptionistlist.html
{% extends 'studenttemplates/studentbase.html' %}
{% load static %}
{% block active2 %} active {% endblock %}
{% block css %}

{% endblock %}
{% block body %}
<div class="card-block">
<div class="dt-responsive table-responsive">
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>user</th>
<th>Name</th>
<th>Address</th>

<th>Email</th>
</tr>
</thead>
<tbody>
    {% for reception in studentreceptionistlist %}
<tr>
<td>{{reception.user}}</td>
<td>{{reception.name}}</td>
<td>{{reception.address}}</td>

<td>{{reception.email}}</td>

</tr>
{% endfor %}
</tbody>
<!-- <tfoot>
<tr>
<th>Name</th>
<th>Position</th>
<th>Office</th>
<th>Age</th>
<th>Start date</th>
<th>Salary</th>
</tr>
</tfoot> -->
</table>
</div>
</div>
</div>
{% endblock %}
{% block js %}

{% endblock %}

templates/studenttemplates/studentteacherlist.html
{% extends 'studenttemplates/studentbase.html' %}
{% load static %}
{% block active1 %} active {% endblock %}
{% block css %}

{% endblock %}
{% block body %}
<div class="card-block">
<div class="dt-responsive table-responsive">
<table id="datatables" class="table table-striped table-bordered nowrap" >
<thead>
<tr>
<th>user</th>
<th>Name</th>
<th>Address</th>
<th>Phone</th>
<th>Qualification</th>
<th>Experience</th>


</tr>
</thead>
<tbody>
    {% for teacher in studentteacherlist %}
<tr>
<td>{{teacher.user}}</td>
<td>{{teacher.name}}</td>
<td>{{teacher.address}}</td>
<td>{{teacher.phone}}</td>
<td>{{teacher.qualification}}</td>
<td>{{teacher.experience}}</td>

</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
</div>
{% endblock %}
{% block js %}

{% endblock %}